/**
 * GENERATED FILE — do not edit by hand.
 *
 * Regenerated by `workers/scripts/gen-registry.ts`. The set of imports
 * below is the authoritative list of tools the Worker registers with the
 * MCP SDK at runtime, kept in lockstep with `registry/server.json` by
 * being emitted from the same scan.
 *
 * To add or remove a tool: drop (or delete) a file under
 * `workers/src/tools/` and run `npm run registry:gen`.
 */

import type { AnyToolModule } from "./types.js";

import get_credit_balance from "./get_credit_balance.js";
import tako_agent from "./tako_agent.js";
import tako_agent_start from "./tako_agent_start.js";
import tako_agent_wait from "./tako_agent_wait.js";
import tako_answer from "./tako_answer.js";
import tako_contents from "./tako_contents.js";
import tako_search from "./tako_search.js";

// Cast at the barrel boundary because function parameters are invariant:
// each tool's handler has a narrow input type from its Zod schema, which
// TS will not assign to the erased `AnyToolModule` handler signature.
// Runtime Zod validation inside the MCP SDK narrows safely.
export const TOOL_REGISTRY: ReadonlyArray<AnyToolModule> = [
  get_credit_balance as unknown as AnyToolModule,
  tako_agent as unknown as AnyToolModule,
  tako_agent_start as unknown as AnyToolModule,
  tako_agent_wait as unknown as AnyToolModule,
  tako_answer as unknown as AnyToolModule,
  tako_contents as unknown as AnyToolModule,
  tako_search as unknown as AnyToolModule,
];
