/**
 * GENERATED FILE — do not edit by hand.
 *
 * Regenerated by `workers/scripts/gen-registry.ts`. The set of imports
 * below is the authoritative list of tools the Worker registers with the
 * MCP SDK at runtime, kept in lockstep with `registry/server.json` by
 * being emitted from the same scan.
 *
 * To add or remove a tool: drop (or delete) a file under
 * `workers/src/tools/` and run `npm run registry:gen`.
 */

import type { AnyToolModule } from "./types.js";

import tool_example from "./_example.js";

// Cast at the barrel boundary because function parameters are invariant:
// each tool's handler has a narrow input type from its Zod schema, which
// TS will not assign to the erased `AnyToolModule` handler signature.
// Runtime Zod validation inside the MCP SDK narrows safely.
export const TOOL_REGISTRY: ReadonlyArray<AnyToolModule> = [
  tool_example as unknown as AnyToolModule,
];
