/**
 * Generate Zod schemas from openapi/sdk.yaml `components.schemas`.
 *
 *   tsx scripts/gen-schemas.ts          # write workers/src/generated/schemas.ts
 *   tsx scripts/gen-schemas.ts --check  # exit 1 if the committed file is stale
 *
 * Output is a single ESM module: one `export const <Name> = z…` per component
 * schema, plus `export type <Name> = z.infer<typeof <Name>>`. Intra-document
 * `$ref`s become references to the sibling const (wrapped in `z.lazy` so order
 * and cycles are safe).
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import yaml from "js-yaml";
import { jsonSchemaToZod } from "json-schema-to-zod";
import type { JsonSchemaObject, Refs } from "json-schema-to-zod";

const HERE = dirname(fileURLToPath(import.meta.url));
const SPEC_PATH = resolve(HERE, "../../openapi/sdk.yaml");
const OUT_PATH = resolve(HERE, "../src/generated/schemas.ts");

const HEADER = `/**
 * GENERATED FILE — do not edit by hand.
 * Regenerated by \`workers/scripts/gen-schemas.ts\` from \`openapi/sdk.yaml\`.
 */
import { z } from "zod";
`;

type JsonSchema = Record<string, unknown>;

const REF_PREFIX = "#/components/schemas/";

/**
 * Recursively rewrite every `{ $ref, ...siblings }` node (siblings non-empty)
 * into `{ allOf: [{ $ref }], ...siblings }`.
 *
 * In OpenAPI 3.1 a `$ref` may legally co-exist with sibling keywords
 * (`default`, `description`, parent `required`, etc.). `json-schema-to-zod`'s
 * `$ref` handling (which our parserOverride replaces with a `z.lazy(...)`)
 * short-circuits the whole node and drops those siblings. Wrapping the bare
 * `$ref` in a single-element `allOf` moves the keywords up one level so
 * json-schema-to-zod applies them natively (`.default()` / `.describe()` /
 * `.optional()`), while the now-pure inner `$ref` still hits the override and
 * collapses to `z.lazy(() => Target)` — a single-element `allOf` over one
 * parser-overridden ref does NOT produce a `z.intersection` wrapper.
 */
function liftRefSiblings(node: unknown): unknown {
  if (Array.isArray(node)) return node.map(liftRefSiblings);
  if (node === null || typeof node !== "object") return node;

  const obj = node as JsonSchema;
  const ref = obj["$ref"];
  const keys = Object.keys(obj);
  if (typeof ref === "string" && keys.length > 1) {
    // Pull the `$ref` out into a single-element allOf and keep the siblings at
    // this level. Recurse into the siblings first so nested refs are handled.
    const { $ref, ...siblings } = obj;
    const rewrittenSiblings: JsonSchema = {};
    for (const [k, v] of Object.entries(siblings)) {
      rewrittenSiblings[k] = liftRefSiblings(v);
    }
    return { allOf: [{ $ref }], ...rewrittenSiblings };
  }

  const out: JsonSchema = {};
  for (const [k, v] of Object.entries(obj)) {
    out[k] = liftRefSiblings(v);
  }
  return out;
}

/** Build the module text from a map of component schemas. Exported for tests. */
export function generateZodModule(schemas: Record<string, JsonSchema>): string {
  const names = new Set(Object.keys(schemas));
  const parts: string[] = [HEADER];

  for (const [name, schema] of Object.entries(schemas)) {
    // OpenAPI 3.1 allows `$ref` + sibling keywords; lift the siblings so
    // json-schema-to-zod applies them natively (see liftRefSiblings).
    const prepared = liftRefSiblings(schema);
    // json-schema-to-zod walks the schema; we intercept `$ref` nodes and emit a
    // reference to the sibling generated const (lazy, so declaration order and
    // cycles are safe).
    const body = jsonSchemaToZod(prepared as JsonSchemaObject, {
      module: "none", // emit only the expression; we wrap it ourselves
      zodVersion: 4,
      parserOverride: (node: JsonSchemaObject, _refs: Refs): string | void => {
        const ref = node["$ref"];
        if (typeof ref === "string" && ref.startsWith(REF_PREFIX)) {
          const target = ref.slice(REF_PREFIX.length);
          if (names.has(target)) return `z.lazy(() => ${target})`;
          return "z.unknown()";
        }
        return undefined;
      },
    });
    parts.push(`export const ${name} = ${body};`);
    parts.push(`export type ${name} = z.infer<typeof ${name}>;`);
    parts.push("");
  }

  return parts.join("\n");
}

function loadComponentSchemas(): Record<string, JsonSchema> {
  const spec = yaml.load(readFileSync(SPEC_PATH, "utf8")) as {
    components?: { schemas?: Record<string, JsonSchema> };
  };
  const schemas = spec.components?.schemas;
  if (!schemas || Object.keys(schemas).length === 0) {
    throw new Error(`No components.schemas found in ${SPEC_PATH}`);
  }
  return schemas;
}

function main(): void {
  const check = process.argv.includes("--check");
  const text = generateZodModule(loadComponentSchemas());

  if (check) {
    let current = "";
    try {
      current = readFileSync(OUT_PATH, "utf8");
    } catch {
      current = "";
    }
    if (current !== text) {
      console.error(
        "src/generated/schemas.ts is stale. Run `npm run schemas:gen` and commit the result.",
      );
      process.exit(1);
    }
    return;
  }

  mkdirSync(dirname(OUT_PATH), { recursive: true });
  writeFileSync(OUT_PATH, text, "utf8");
  console.log(`Wrote ${OUT_PATH}`);
}

// Only run main() when invoked as a script, not when imported by tests.
if (process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url))) {
  main();
}
