/**
 * The golden query set: hand-checked routing expectations for the Tako MCP.
 *
 * Separated from the runner so the cases can be reviewed as data. Every
 * expectation here was verified BY HAND against live staging — deliberately
 * not generated by a scorer, because a token-overlap scorer was measured to
 * over-credit (it passed `metric="employees"` → `Revenue Per Employee`, which
 * is not headcount, and `same store sales` → `Drug Retail Same Store Sales`,
 * the wrong sector).
 *
 * WHAT THESE ASSERT, AND WHY IT IS SHAPED THIS WAY
 *
 * Invariants, never fixtures. The retrieval backend is nondeterministic: the
 * same `tako_search` request returned 1, then 2, then 1 cards across three
 * consecutive runs. Asserting exact card sets or counts would flake on day
 * one. So the assertions are of the form "the entity resolves to something
 * containing X", "found is true", "a next_call is emitted" — properties that
 * hold across runs.
 *
 * The graph endpoints, by contrast, ARE deterministic (candidate order, names,
 * aliases and coverage totals were all identical across five runs), which is
 * what makes resolution expectations stable enough to pin at all.
 */

/** One golden case: a call, and the properties its result must satisfy. */
export interface GoldenCase {
  /** Short stable id, used in output and to skip/select cases. */
  id: string;
  /** Why this case exists — usually the bug it pins. */
  why: string;
  args: { q: string; metric?: string; label?: string; types?: "entity" | "metric" };
  expect: {
    /** Substring the resolved entity name must contain (case-insensitive). */
    entity?: string;
    /** Substring the resolved metric name must contain (case-insensitive). */
    metric?: string;
    found?: boolean;
    /** Whether a runnable next_call must be present. */
    nextCall?: boolean;
    /** Substrings that must NOT appear anywhere in the rendered text. */
    absent?: string[];
    /** Substrings that must appear in the rendered text. */
    present?: string[];
    /** Cap on response size — the lookup path must stay small. */
    maxChars?: number;
  };
}

export const GOLDEN_CASES: GoldenCase[] = [
  // ---- lookup path: the common shapes must resolve -----------------------
  {
    id: "lookup-basic",
    why: "the canonical entity+metric pair",
    args: { q: "Nvidia", metric: "gross margin" },
    expect: { entity: "NVIDIA", metric: "Gross Margin", found: true, nextCall: true, maxChars: 2000 },
  },
  {
    id: "lookup-plural",
    why: "metric names are morphological variants; gating on tokens once promoted `Avnet Revenue Total Revenue` over `Revenues`",
    args: { q: "Apple", metric: "revenue" },
    expect: { entity: "Apple", metric: "Revenue", found: true, nextCall: true },
  },
  {
    id: "lookup-abbreviation",
    why: "`capex` shares no token with `Capital Expenditure` — it matches only through an alias narrower than the query",
    args: { q: "Chevron", metric: "capex" },
    expect: { entity: "Chevron", metric: "Capital Expenditure", found: true, nextCall: true },
  },
  {
    id: "lookup-alias-only-metric",
    why: "ROA has NO name match at all; requiring one would break it",
    args: { q: "Apple", metric: "ROA" },
    expect: { metric: "Return on Assets", found: true, nextCall: true },
  },
  {
    id: "lookup-macro",
    why: "macro entities resolve through a different source family",
    args: { q: "Japan", metric: "unemployment rate" },
    expect: { entity: "Japan", metric: "Unemployment", found: true, nextCall: true },
  },
  {
    id: "lookup-verbatim-name",
    why: "a pasted-back full metric name ranked below the generic one and fell outside the shown candidates",
    args: { q: "United States", metric: "CPI Inflation Rate (Seasonally Adjusted)" },
    expect: { metric: "CPI Inflation Rate (Seasonally Adjusted)", found: true, nextCall: true },
  },

  // ---- the relevance gate: wrong entities must not be reported ----------
  {
    id: "gate-poisoned-alias",
    why: "Cuscal Limited carries `Carnival Corporation` as an alias; a name match must outrank an alias match",
    args: { q: "Carnival Corporation", metric: "passenger cruise days" },
    expect: { entity: "Carnival", found: true, absent: ["Cuscal"] },
  },
  {
    id: "gate-fuzzy-entity",
    why: "`UnitedHealth Group` used to spend half its drill budget on Blackstone",
    args: { q: "UnitedHealth Group" },
    expect: { entity: "UnitedHealth", found: true, absent: ["Blackstone Inc. (ORG)** —"] },
  },
  {
    id: "gate-depth",
    why: "Carnival's first ranks are zero-coverage name variants; the covered node sits deeper",
    args: { q: "Carnival" },
    expect: { found: true, present: ["Carnival Corporation Ltd."] },
  },

  // ---- honest gaps: these must NOT claim coverage ------------------------
  {
    id: "gap-nonsense-phrase",
    why: "a plausible phrase always partially matches something; this reported 250+ metrics on Tuesday Morning Corporation",
    args: { q: "the vibes of tuesday" },
    expect: { found: false, nextCall: false, maxChars: 600 },
  },
  {
    id: "gap-gibberish",
    why: "no node at all — the one case that was always handled correctly",
    args: { q: "zzzqqxyw" },
    expect: { found: false, nextCall: false, maxChars: 600 },
  },
  {
    id: "gap-nonsense-metric",
    why: "`number of unicorns` matched `Colombia Number Of Customers` on the token `number` and emitted a runnable PRICED call",
    args: { q: "Tesla", metric: "number of unicorns" },
    expect: { found: false, nextCall: false },
  },
  {
    id: "gap-superset-alias",
    why: "`Employment Index` vouched for itself via the broader alias `employment level index`",
    args: { q: "S&P 500", metric: "index level" },
    expect: { found: false, nextCall: false },
  },
  {
    id: "gap-domain-routing",
    why: "openai.com has no graph node while SimilarWeb still covers it — must route, not dead-end",
    args: { q: "openai.com", metric: "monthly visits" },
    expect: { found: false, nextCall: false, present: ["tako_search"] },
  },

  // ---- next_call must actually populate --------------------------------
  {
    id: "next-call-metric-named",
    why: "next_call was null on 11/11 probed names; naming a metric in `q` now yields a handle",
    args: { q: "Inflation Rate" },
    expect: { found: true, nextCall: true, present: ['"strict":true'] },
  },
  {
    id: "next-call-no-invented-entity",
    why: "the metric branch used to pair with coverage.items[0], producing 'NVIDIA Corporation Passenger Cruise Days' to run verbatim",
    args: { q: "Passenger Cruise Days" },
    expect: { found: true, nextCall: true, absent: ["NVIDIA Corporation Passenger Cruise Days"] },
  },
  {
    id: "next-call-entity-only-stays-null",
    why: "a bare company names no measure, so a runnable handle would spend a priced call on an arbitrary metric",
    args: { q: "UnitedHealth Group" },
    expect: { found: true, nextCall: false },
  },

  // ---- malformed input must fail visibly, not confidently ---------------
  {
    id: "swapped-args",
    why: "q=metric/metric=entity used to return found:true with a runnable next_call for garbage",
    args: { q: "gross margin", metric: "Nvidia" },
    expect: { found: false, nextCall: false, present: ["look swapped", 'q="Nvidia"'] },
  },
  {
    id: "swapped-args-no-false-positive",
    why: "`Block` ranks the metric `Blocked Shots` first; a type-only rule would flag this correct call",
    args: { q: "Block", metric: "same store sales" },
    expect: { found: true, absent: ["look swapped"] },
  },

  // ---- the pin form: every handle must be metric-only + strict ----------
  {
    id: "pin-form",
    why: "an entity-only pin, or a pin without strict, was measured to be a no-op",
    args: { q: "Microsoft", metric: "net income" },
    expect: { found: true, nextCall: true, present: ['"strict":true'] },
  },
];

/** Cases whose next_call must be executed and produce a card. Kept small —
 *  each one spends a priced call. */
export const EXECUTABLE_CASE_IDS = ["lookup-basic", "lookup-plural", "lookup-macro"];
